bazinga_geocoder:
    providers:
        google_maps:
            factory: Bazinga\GeocoderBundle\ProviderFactory\GoogleMapsFactory
            locale: fr
            options:
                region: null
                api_key: '%chaplean_geolocation.api_key%'
